// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'), 
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  icChat: require('../Images/Icons/icon_chat.png'),
  icGroup: require('../Images/Icons/icon_group.png'),
  icRadioPause: require('../Images/Icons/icon_radio_pause.png'),
  icRadioPlay: require('../Images/Icons/icon_radio_play.png'),
  icRecordBig: require('../Images/Icons/icon_record.png'),
  microOpened: require('../Images/Icons/microphone_open.png'),
  icProfile: require('../Images/Icons/icon_profile.png'),
  users: require('../Images/Icons/users.png'),
  avatar12: require('../Images/avatar12.png'),
  alertIcon: require('../Images/alert.png'),
  avatar1: require('../Images/avatar1.png'),
  avatar2: require('../Images/avatar2.png'),
  avatar3: require('../Images/avatar3.png'),
  avatar4: require('../Images/avatar4.png'),
  avatar5: require('../Images/avatar5.png'),
  avatar7: require('../Images/avatar7.png'),
  avatar8: require('../Images/avatar8.png'),
  avatar9: require('../Images/avatar9.png'),
  avatar10: require('../Images/avatar10.png'),
  avatar11: require('../Images/avatar11.png'),
  avatar12: require('../Images/avatar12.png'),
  play: require('../Images/play.png'),
  stop: require('../Images/stop.png'),
  navBar: require('../Images/navBar.png'),
  parking: require('../Images/MapIcon/parking.png'),
  activeParking: require('../Images/MapIcon/activeParking.png'),
  alertZone: require('../Images/MapIcon/alertZone.png'),
  activeAlertZone: require('../Images/MapIcon/activeAlertZone.png'),
  marker: require('../Images/MapIcon/marker.png'),
  bottomMenu: require('../Images/bottom_menu.png'),
  privateBackground: require('../Images/private_background.jpg'),
  smallMap: require('../Images/small_map.png'),
  emojis: {
    smile: require('../Images/Shyly_Smiling_Face_Emoji.png')
  },
  white_logo: require('../Images/white_logo.png'),

}

export default images
